import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import MaxWidthRapper from "@/components/reuseable/MaxWidthRapper";
import { DarkThemeProvider } from "@/provider/DarkThemeProvider";

const os = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={os.className}>
				<DarkThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					
					<MaxWidthRapper classN="flex flex-col pb-5">
						<Navbar />
						{children}
						<Footer />
					</MaxWidthRapper>
				</DarkThemeProvider>
			</body>
		</html>
	);
}
